services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - ./custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
      - ../CERTIFICADO:/etc/nginx/certs:ro
      
  db:
    image: mariadb:10.4.28
    container_name: unw-db
    restart: always
    environment:
      MYSQL_DATABASE: unw
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wpuserpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
      - ./unw.24.07.14.46.sql:/docker-entrypoint-initdb.d/unw.sql
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:php8.2-apache
    container_name: unw-wp
    restart: always
    depends_on:
      - db
      - nginx-proxy
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: unw
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wpuserpass
    volumes:
      - .:/var/www/html

volumes:
  db_data:
  conf:
  html: