version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - "./custom_proxy_settings_seek.conf:/etc/nginx/conf.d/custom_proxy_settings.conf"
     
  docker-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.nginx-proxy.docker-gen"
      
  db:
    image: mariadb:10.4.28
    container_name: unw-db
    restart: always
    environment:
      MYSQL_DATABASE: unw
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wpuserpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
      - ./unw.19.08.25.sql:/docker-entrypoint-initdb.d/unw.sql
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:php8.2-apache
    container_name: unw-wp
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: unw
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wpuserpass
      VIRTUAL_HOST: uwiener.btechcloud.pe
      VIRTUAL_PORT: 80
      VIRTUAL_PATH: /www-02
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://uwiener.btechcloud.pe/www-02');
        define('WP_SITEURL', 'http://uwiener.btechcloud.pe/www-02');
        define('FORCE_SSL_ADMIN', false);
        define('FORCE_SSL_LOGIN', false);

    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"

volumes:
  db_data:
  conf:
  vhost:
  html: