version: '3.8'

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - "./nginx-simple.conf:/etc/nginx/conf.d/default.conf"
     
  db:
    image: mariadb:10.4.28
    container_name: unw-db
    restart: always
    environment:
      MYSQL_DATABASE: unw
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wpuserpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
      - ./unw.19.08.25.sql:/docker-entrypoint-initdb.d/unw.sql
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:php8.2-apache
    container_name: unw-wp
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: unw
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wpuserpass
    user: "1000:1000"  # Usuario con permisos adecuados
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"

volumes:
  db_data:
  conf:
  vhost:
  html: